### ISSUE TITLE
Standard optimization test functions

### ISSUE THREAD

**Issue by alejandrom247** [jairodelgado/dnn_opt#6]
I want to implement a series of test functions to validate the performance of the optimization algorithms used in the dnn_opt library.

**Comment by jairodelgado** [comment]
I would suggest being explicit about the test functions you want to implement, I think these shuould suffice for this issue:

- [x] 25. Brown Function
- [x] 34. Chung Reynolds Function
- [x] 38. Cosine Mixture Function
- [x] 40. Csendes Function
- [x] 43. Deb 1 Function
- [x] 44. Deb 3 Function
- [x] 48. Dixon & Price Function
- [x] 53. Egg Holder Function
- [x] 54. Exponential Function
- [x] 57. Giunta Function

Each function specification can be found in: [http://arxiv.org/abs/1308.4008v1](http://arxiv.org/abs/1308.4008v1)

Also let's limit the scope of this issue to sequential implementation in the core layer.

**Comment by jairodelgado** [comment]
Also please consider a more appropiate name for the new branch you have created. I would suggest something like: test-functions-alejandro

**Comment by jairodelgado** [comment]
As the number of benchmark functions is growing, in order to keep the code organized we are creating a new namespace within solutions (`dnn_opt::core::solutions::bench`). A corresponding folder has been created to this end. See b5cbe901d80d3b2724dd2ba07817c3cba9c9d579 and f46bbbe9729e1cf2f8a5eb4c0d9063ab637d89e6.
